# Generated by Django 4.1.3 on 2022-12-03 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverworkermodel',
            name='message_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_worker_message_to', to='Driver.usermodel'),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='message_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_message_to', to='Driver.usermodel'),
        ),
    ]
