# Generated by Django 4.1.3 on 2022-11-27 14:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=128)),
                ('phone_number', models.CharField(max_length=15, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: "+00000000000". Up to 14 digits allowed.', regex='^(\\+\\d{2,3})?\\d{9,11}$')])),
                ('user_type', models.CharField(choices=[(1, 'Admin'), (2, 'Manager'), (3, 'Personnel'), (4, 'Dispatcher'), (5, 'Forwarder'), (6, 'Driver')], max_length=24)),
            ],
        ),
        migrations.AddField(
            model_name='cargomodel',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plancargomodel',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cargomodel',
            name='company_address_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_company_address_from', to='Driver.addresscompanyfrommodel'),
        ),
        migrations.AlterField(
            model_name='cargomodel',
            name='company_address_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_company_address_to', to='Driver.addresscompanytomodel'),
        ),
        migrations.AlterField(
            model_name='cargomodel',
            name='forwarder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_forwarder', to='Driver.forwardermodel'),
        ),
        migrations.AlterField(
            model_name='cargomodel',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_truck', to='Driver.carmodel'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='trailer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car_trailer', to='Driver.trailermodel'),
        ),
        migrations.AlterField(
            model_name='plancargomodel',
            name='description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_cargo_description', to='Driver.cargomodel'),
        ),
        migrations.AlterField(
            model_name='plancargomodel',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_cargo_driver', to='Driver.drivermodel'),
        ),
        migrations.AlterField(
            model_name='plancargomodel',
            name='forwarder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_cargo_forwarder', to='Driver.forwardermodel'),
        ),
        migrations.AlterField(
            model_name='plancargomodel',
            name='truck',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_cargo_truck', to='Driver.carmodel'),
        ),
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('message_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_message_to', to='Driver.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='DriverWorkerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('confirm_arrival', models.CharField(choices=[(1, 'Positive')], max_length=32)),
                ('confirm_unloading', models.CharField(choices=[(1, 'Positive')], max_length=32)),
                ('confirm_loading', models.CharField(choices=[(1, 'Positive')], max_length=32)),
                ('raport', models.CharField(choices=[(1, 'Positive'), (2, 'Raport problem')], max_length=32)),
                ('message', models.TextField()),
                ('message_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_worker_message_to', to='Driver.usermodel')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_worker_point', to='Driver.plancargomodel')),
            ],
        ),
    ]
