# Generated by Django 4.1.3 on 2022-12-08 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0005_alter_carmodel_car_trailer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='car_trailer_name',
            new_name='car_trailer',
        ),
    ]
