# Generated by Django 4.1.3 on 2022-12-08 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0006_rename_car_trailer_name_carmodel_car_trailer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='car_trailer',
            new_name='trailer',
        ),
    ]
