# Generated by Django 4.1.3 on 2022-12-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0008_alter_carmodel_cargo_space_alter_carmodel_have_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='cargo_space',
            field=models.CharField(choices=[('truck', 'Truck'), ('8', '8 euro pallets'), ('9', '9 euro pallets'), ('10', '10 euro pallets'), ('12', '12 euro pallets'), ('18', '18 euro pallets'), ('19', '19 euro pallets')], max_length=15),
        ),
        migrations.AlterField(
            model_name='trailermodel',
            name='cargo_space',
            field=models.CharField(choices=[('8', '8 euro pallets'), ('9', '9 euro pallets'), ('10', '10 euro pallets'), ('12', '12 euro pallets'), ('18', '18 euro pallets'), ('19', '19 euro pallets'), ('20', '20 euro pallets'), ('32', '32 euro pallets'), ('33', '33 euro pallets'), ('36', '36 euro pallets')], max_length=15),
        ),
    ]
